// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeter.djinni

#import "HSFLGreeter+Private.h"
#import "HSFLGreeter.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface HSFLGreeter ()

- (id)initWithCpp:(const std::shared_ptr<::libgreeter::Greeter>&)cppRef;

@end

@implementation HSFLGreeter {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::libgreeter::Greeter>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::libgreeter::Greeter>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable HSFLGreeter *)createGreeter {
    try {
        auto objcpp_result_ = ::libgreeter::Greeter::create_greeter();
        return ::djinni_generated::Greeter::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)welcomeFromCpp {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->welcomeFromCpp();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Greeter::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Greeter::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<HSFLGreeter>(cpp);
}

}  // namespace djinni_generated

@end
