// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeter.djinni

#import <Foundation/Foundation.h>
@class HSFLGreeter;


@interface HSFLGreeter : NSObject

+ (nullable HSFLGreeter *)createGreeter;

- (nonnull NSString *)welcomeFromCpp;

@end
