// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeter.djinni

package com.hsfl.greeter.djinni;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Greeter {
    public abstract String welcomeFromCpp();

    public static native Greeter createGreeter();

    private static final class CppProxy extends Greeter
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String welcomeFromCpp()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_welcomeFromCpp(this.nativeRef);
        }
        private native String native_welcomeFromCpp(long _nativeRef);
    }
}
