// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeter.djinni

#pragma once

#include "djinni_support.hpp"
#include "greeter.hpp"

namespace djinni_generated {

class NativeGreeter final : ::djinni::JniInterface<::libgreeter::Greeter, NativeGreeter> {
public:
    using CppType = std::shared_ptr<::libgreeter::Greeter>;
    using CppOptType = std::shared_ptr<::libgreeter::Greeter>;
    using JniType = jobject;

    using Boxed = NativeGreeter;

    ~NativeGreeter();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeGreeter>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeGreeter>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeGreeter();
    friend ::djinni::JniClass<NativeGreeter>;
    friend ::djinni::JniInterface<::libgreeter::Greeter, NativeGreeter>;

};

}  // namespace djinni_generated
