// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeter.djinni

#pragma once

#include <memory>
#include <string>

namespace libgreeter {

class Greeter {
public:
    virtual ~Greeter() {}

    static std::shared_ptr<Greeter> create_greeter();

    virtual std::string welcomeFromCpp() = 0;
};

}  // namespace libgreeter
